SELECT [Report_Date]
      ,[Account_Number]
      ,[Card_Number]
      ,[Customer_Name]
      ,[Business]
      ,[Reporting_Portfolio]
      ,[GCV]
      ,[PV]
      ,[Outstanding_Balance]
      ,[Outstanding_Principal]
      ,[Stage]
      ,[Write_Off_Year]
      ,[Write_Off_Month]
      ,[Load_Date]
      ,[Last_Call_Date]
      ,[Call_Time]
      ,[Days_Last_Called]
      ,[Last_Called_Date_Bucket]
      ,[Last_Called_By]
      ,[Last_Call_Outcome]
      ,[Last_Call_Disposition]
      ,[Call_Type]
      ,[Last_PP_Date]
      ,[Days_Last_PP]
      ,[Last_PP_Date_Bucket]
      ,[Commission_Owner]
      ,[Installment_Amount]
      ,[Plan_Balance]
      ,[Last_Action_Date]
      ,[Days_Last_Actioned]
      ,[Last_Action_Date_Bucket] as 'Last Touch'
      ,[3_Days_Not_Called]
      ,[3_Days_Not_Actioned]
      ,[New_Load_Not_Called]
      ,[30_Days_Not_Actioned]
      ,[Unit]
      ,[Plan_Status]
      ,[Principal_Value]
      ,[debt_amount]
      ,[Last_Task]
      ,[Last_Task_Date]
      ,[Product_Type]
      ,[Takeover_Memo]
  FROM [Report].[vw_Account_Breakdown_TH]
  WHERE Reporting_Portfolio IS NOT NULL
  AND Business = 'Debt Purchase'
  AND Last_Action_Date_Bucket NOT IN ('09. Unknown')
  AND Country IN ('Thailand')
  AND Stage NOT IN ('Pending Close Review','Pending Paid Review','Closed','Outsourcing')
